"""use the autogenerate feature

Revision ID: a8891012f6b4
Revises: 4116d6145eee
Create Date: 2021-11-26 10:00:53.322498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8891012f6b4'
down_revision = '4116d6145eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
